USE datakzo

SELECT * into #TempClaims FROM EDICLDPF 
WHERE CDF_PRVID = 2450
--and CDF_CLTID = 00125789 


--So this needs to be expanded so that you are selecting the provider.
select SALS.*,REVCodes.CR_CODE into #TEMPSALS from PCHSALPF SALS
JOIN PCHXSPPF CPTCrosswalk ON SALS.SAF_XSPID = CPTCrosswalk.XP_RCDID   
LEFT JOIN PCHCPTPF REVCodes ON CPTCrosswalk.XPF_CPTID = REVCodes.CR_RCDID 
where SAF_PRVID = 2450
AND REVCodes.CR_CODE NOT IN('T1040')

select * from #TempClaims TC
LEFT JOIN #TEMPSALS TS ON TC.CDF_CLTID = TS.SAF_CLTID AND TC.CD_PROCCD = TS.CR_CODE AND TC.CD_FRMDT = TS.SA_SRVDATE AND TC.CD_UNITS = TS.SA_UNITS AND TC.CD_THRTM = TS.SA_ENDTIME

select * into #resultSet from #TempClaims TC
LEFT JOIN #TEMPSALS TS ON TC.CDF_CLTID = TS.SAF_CLTID AND TC.CD_PROCCD = TS.CR_CODE AND TC.CD_FRMDT = TS.SA_SRVDATE AND TC.CD_UNITS = TS.SA_UNITS AND TC.CD_THRTM = TS.SA_ENDTIME

select * from #resultSet

SELECT R1.CDF_CLMID as 'Claim ID',SA_RCDID as 'SAL ID'  from #resultSet R1